"""items=["KK", "DK", "AGD", "Harry",int,float,"double", 1, 5, 9, 25, 99, 105]
for item in items:
    print(item)
    if str(item).isnumeric():
        print(item)"""
""""""


"""marks = [["Keshaw", 10],
         ["Arko", 9.9],
         ["Keshav", 9.8],
         ["Aniket", 9.7],
         ["TPG", 9.4],
         ["Nikhil", 9.3],
         ["Harsh", 9.2],
         ["Rahul", 9.1],
         ["Shivam", 9.0],
         ["Vivek", 9.5]]
dict1=dict(marks)
for item in dict1:
    print(item)
for item, cgpa in dict1.items():
    print(item, "and cgpa is ", cgpa)"""